In [14]:
#pip install requests
#pip install openpyxl
#pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     -------------------------------------- 112.2/112.2 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: webencodings in c:\users\usuario\anaconda3\envs\deeplearning-labs\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\users\usuario\anaconda3\envs\deeplearning-labs\lib\site-packages (from html5lib) (1.16.0)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Note: you may need to restart the kernel to use updated packages.

# Extracción de tablas de equipos

In [1]:
# import pandas as pd
# import requests
# import openpyxl# Add this line to import the requests library
# import html5lib

# #fbref_url = 'https://fbref.com/en/comps/32/2022-2023/misc/2022-2023-Primeira-Liga-Stats'
# #fbref_url = 'https://fbref.com/en/comps/Big5/2017-2018/stats/players/2017-2018-Big-5-European-Leagues-Stats'
# # fbref_url = 'https://fbref.com/en/comps/Big5/2017-2018/defense/players/2017-2018-Big-5-European-Leagues-Stats'
# #fbref_url = 'https://fbref.com/en/comps/Big5/2022-2023/2022-2023-Big-5-European-Leagues-Stats'
# fbref_url = 'https://fbref.com/en/comps/Big5/2023-2024/passing/players/2023-2024-Big-5-European-Leagues-Stats'
# # Replaces comment start and end with blank to find the player table
# df = pd.read_html(requests.get(fbref_url).text.replace('<!--', '').replace('-->', ''), attrs={'id':'stats_defense'}, index_col=[0])[0]
# #stats_standard
# #stats_misc
# #stats_possession
# #stats_shooting
# #stats_passing
# #stats_gca
# #stats_defense

# df.columns = df.columns.get_level_values(1)

# df = df.reset_index().rename(columns={'index': 'Player_id'})

# df = df[df['Player_id'] != 'Rk']

# df = df.fillna(0)
# df

In [2]:
# # Guardar el DataFrame en un archivo Excel
# nombre_archivo_excel = 'BigFive2324Passing.xlsx'
# df.to_excel(nombre_archivo_excel, index=False)

# print(f'DataFrame guardado en {nombre_archivo_excel}')

In [3]:
# Hacer scraping para cada una de las 7 estadísticas 
import pandas as pd
import numpy

url_df2324 = "https://fbref.com/en/comps/Big5/2023-2024/shooting/squads/2023-2024-Big-5-European-Leagues-Stats"

df = pd.read_html(url_df2324)[0]
df

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Standard                         ...  \
                 # Pl                90s      Gls   Sh  SoT  SoT%  Sh/90  ...
0                  30               38.0       33  458  136  29.7  12.05  ...
1                  35               38.0       42  478  163  34.1  12.58  ...
2                  25               38.0       86  647  209  32.3  17.03  ...
3                  31               38.0       72  511  182  35.6  13.45  ...
4                  29               38.0       72  539  197  36.5  14.18  ...
..                ...                ...      ...  ...  ...   ...    ...  ...
91                 32               38.0       64  462  163  35.3  12.16  ...
92                 30               34.0       45  407  125  30.7  11.97  ...
93                 26               38.0       58  445  146  32.8  11.71  ...
94                 28               34.0       41  411  147  35.8  12.09  ...
95                 27               38.0       47  425  153  36.0  11.18  ...

                             Expected
   G/SoT  Dist  FK  PK PKatt       xG  npxG npxG/Sh  G-xG np:G-xG
0   0.22  17.7  15   3     7     46.2  40.7    0.09 -13.2   -10.7
1   0.25  18.8  18   2     2     48.7  47.1    0.10  -6.7    -7.1
2   0.36  15.8   6  10    10     76.1  68.5    0.11   9.9     7.5
3   0.37  16.0  15   4     4     63.3  60.3    0.12   8.7     7.7
4   0.34  16.0   6   5     5     57.8  53.9    0.10  14.2    13.1
..   ...   ...  ..  ..   ...      ...   ...     ...   ...     ...
91  0.36  16.2   8   5     7     55.6  50.1    0.11   8.4     8.9
92  0.32  17.4  14   5     6     46.9  42.0    0.10  -1.9    -2.0
93  0.37  16.2  17   4     5     52.3  48.4    0.11   5.7     5.6
94  0.27  17.7  17   2     3     39.2  36.7    0.09   1.8     2.3
95  0.28  16.7  12   4     4     46.7  43.6    0.11   0.3    -0.6

[96 rows x 22 columns]

In [4]:
df = pd.read_html(url_df2324)
df = df[0]  
df

   Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                   Rk              Squad                Comp
0                   1             Alavés          es La Liga
1                   2            Almería          es La Liga
2                   3            Arsenal  eng Premier League
3                   4        Aston Villa  eng Premier League
4                   5           Atalanta          it Serie A
..                ...                ...                 ...
91                 92         Villarreal          es La Liga
92                 93      Werder Bremen       de Bundesliga
93                 94           West Ham  eng Premier League
94                 95          Wolfsburg       de Bundesliga
95                 96             Wolves  eng Premier League

   Unnamed: 3_level_0 Unnamed: 4_level_0 Standard                         ...  \
                 # Pl                90s      Gls   Sh  SoT  SoT%  Sh/90  ...
0                  30               38.0       33  458  136  29.7  12.05  ...
1                  35               38.0       42  478  163  34.1  12.58  ...
2                  25               38.0       86  647  209  32.3  17.03  ...
3                  31               38.0       72  511  182  35.6  13.45  ...
4                  29               38.0       72  539  197  36.5  14.18  ...
..                ...                ...      ...  ...  ...   ...    ...  ...
91                 32               38.0       64  462  163  35.3  12.16  ...
92                 30               34.0       45  407  125  30.7  11.97  ...
93                 26               38.0       58  445  146  32.8  11.71  ...
94                 28               34.0       41  411  147  35.8  12.09  ...
95                 27               38.0       47  425  153  36.0  11.18  ...

                             Expected
   G/SoT  Dist  FK  PK PKatt       xG  npxG npxG/Sh  G-xG np:G-xG
0   0.22  17.7  15   3     7     46.2  40.7    0.09 -13.2   -10.7
1   0.25  18.8  18   2     2     48.7  47.1    0.10  -6.7    -7.1
2   0.36  15.8   6  10    10     76.1  68.5    0.11   9.9     7.5
3   0.37  16.0  15   4     4     63.3  60.3    0.12   8.7     7.7
4   0.34  16.0   6   5     5     57.8  53.9    0.10  14.2    13.1
..   ...   ...  ..  ..   ...      ...   ...     ...   ...     ...
91  0.36  16.2   8   5     7     55.6  50.1    0.11   8.4     8.9
92  0.32  17.4  14   5     6     46.9  42.0    0.10  -1.9    -2.0
93  0.37  16.2  17   4     5     52.3  48.4    0.11   5.7     5.6
94  0.27  17.7  17   2     3     39.2  36.7    0.09   1.8     2.3
95  0.28  16.7  12   4     4     46.7  43.6    0.11   0.3    -0.6

[96 rows x 22 columns]

In [5]:
df.columns = [' '.join(col).strip() for col in df.columns]

df = df.reset_index(drop=True)
df

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Squad,Unnamed: 2_level_0 Comp,Unnamed: 3_level_0 # Pl,Unnamed: 4_level_0 90s,Standard Gls,Standard Sh,Standard SoT,Standard SoT%,Standard Sh/90,...,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG
0,1,Alavés,es La Liga,30,38.0,33,458,136,29.7,12.05,...,0.22,17.7,15,3,7,46.2,40.7,0.09,-13.2,-10.7
1,2,Almería,es La Liga,35,38.0,42,478,163,34.1,12.58,...,0.25,18.8,18,2,2,48.7,47.1,0.10,-6.7,-7.1
2,3,Arsenal,eng Premier League,25,38.0,86,647,209,32.3,17.03,...,0.36,15.8,6,10,10,76.1,68.5,0.11,9.9,7.5
3,4,Aston Villa,eng Premier League,31,38.0,72,511,182,35.6,13.45,...,0.37,16.0,15,4,4,63.3,60.3,0.12,8.7,7.7
4,5,Atalanta,it Serie A,29,38.0,72,539,197,36.5,14.18,...,0.34,16.0,6,5,5,57.8,53.9,0.10,14.2,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,Villarreal,es La Liga,32,38.0,64,462,163,35.3,12.16,...,0.36,16.2,8,5,7,55.6,50.1,0.11,8.4,8.9
92,93,Werder Bremen,de Bundesliga,30,34.0,45,407,125,30.7,11.97,...,0.32,17.4,14,5,6,46.9,42.0,0.10,-1.9,-2.0
93,94,West Ham,eng Premier League,26,38.0,58,445,146,32.8,11.71,...,0.37,16.2,17,4,5,52.3,48.4,0.11,5.7,5.6
94,95,Wolfsburg,de Bundesliga,28,34.0,41,411,147,35.8,12.09,...,0.27,17.7,17,2,3,39.2,36.7,0.09,1.8,2.3
95,96,Wolves,eng Premier League,27,38.0,47,425,153,36.0,11.18,...,0.28,16.7,12,4,4,46.7,43.6,0.11,0.3,-0.6

In [6]:
new_columns = []
for col in df.columns:
    if 'level_0' in col:
        new_col = col.split()[-1]
    else:
        new_col = col
    new_columns.append(new_col)

df.columns = new_columns
df = df.fillna(0)

df.head()

,Rk,Squad,Comp,Pl,90s,Standard Gls,Standard Sh,Standard SoT,Standard SoT%,Standard Sh/90,...,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG
0,1,Alavés,es La Liga,30,38.0,33,458,136,29.7,12.05,...,0.22,17.7,15,3,7,46.2,40.7,0.09,-13.2,-10.7
1,2,Almería,es La Liga,35,38.0,42,478,163,34.1,12.58,...,0.25,18.8,18,2,2,48.7,47.1,0.10,-6.7,-7.1
2,3,Arsenal,eng Premier League,25,38.0,86,647,209,32.3,17.03,...,0.36,15.8,6,10,10,76.1,68.5,0.11,9.9,7.5
3,4,Aston Villa,eng Premier League,31,38.0,72,511,182,35.6,13.45,...,0.37,16.0,15,4,4,63.3,60.3,0.12,8.7,7.7
4,5,Atalanta,it Serie A,29,38.0,72,539,197,36.5,14.18,...,0.34,16.0,6,5,5,57.8,53.9,0.10,14.2,13.1

In [7]:
pd.set_option('display.max_columns', None)

df.head()

,Rk,Squad,Comp,Pl,90s,Standard Gls,Standard Sh,Standard SoT,Standard SoT%,Standard Sh/90,Standard SoT/90,Standard G/Sh,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG
0,1,Alavés,es La Liga,30,38.0,33,458,136,29.7,12.05,3.58,0.07,0.22,17.7,15,3,7,46.2,40.7,0.09,-13.2,-10.7
1,2,Almería,es La Liga,35,38.0,42,478,163,34.1,12.58,4.29,0.08,0.25,18.8,18,2,2,48.7,47.1,0.10,-6.7,-7.1
2,3,Arsenal,eng Premier League,25,38.0,86,647,209,32.3,17.03,5.50,0.12,0.36,15.8,6,10,10,76.1,68.5,0.11,9.9,7.5
3,4,Aston Villa,eng Premier League,31,38.0,72,511,182,35.6,13.45,4.79,0.13,0.37,16.0,15,4,4,63.3,60.3,0.12,8.7,7.7
4,5,Atalanta,it Serie A,29,38.0,72,539,197,36.5,14.18,5.18,0.12,0.34,16.0,6,5,5,57.8,53.9,0.10,14.2,13.1

In [8]:
# df = df.drop(columns=['R k','C o u n t r y','M P', 'W', 'D', 'L', 'G F', 'G A', 'G D', 'P t s', 'P t s / M P', 'x G', 'x G A', 'x G D', 'x G D / 9 0', 'A t t e n d a n c e', 'T o p   T e a m   S c o r e r', 'G o a l k e e p e r'])

In [9]:
df_clean = df.drop(columns=['Rk'])

In [10]:
df_clean

,Squad,Comp,Pl,90s,Standard Gls,Standard Sh,Standard SoT,Standard SoT%,Standard Sh/90,Standard SoT/90,Standard G/Sh,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG
0,Alavés,es La Liga,30,38.0,33,458,136,29.7,12.05,3.58,0.07,0.22,17.7,15,3,7,46.2,40.7,0.09,-13.2,-10.7
1,Almería,es La Liga,35,38.0,42,478,163,34.1,12.58,4.29,0.08,0.25,18.8,18,2,2,48.7,47.1,0.10,-6.7,-7.1
2,Arsenal,eng Premier League,25,38.0,86,647,209,32.3,17.03,5.50,0.12,0.36,15.8,6,10,10,76.1,68.5,0.11,9.9,7.5
3,Aston Villa,eng Premier League,31,38.0,72,511,182,35.6,13.45,4.79,0.13,0.37,16.0,15,4,4,63.3,60.3,0.12,8.7,7.7
4,Atalanta,it Serie A,29,38.0,72,539,197,36.5,14.18,5.18,0.12,0.34,16.0,6,5,5,57.8,53.9,0.10,14.2,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Villarreal,es La Liga,32,38.0,64,462,163,35.3,12.16,4.29,0.13,0.36,16.2,8,5,7,55.6,50.1,0.11,8.4,8.9
92,Werder Bremen,de Bundesliga,30,34.0,45,407,125,30.7,11.97,3.68,0.10,0.32,17.4,14,5,6,46.9,42.0,0.10,-1.9,-2.0
93,West Ham,eng Premier League,26,38.0,58,445,146,32.8,11.71,3.84,0.12,0.37,16.2,17,4,5,52.3,48.4,0.11,5.7,5.6
94,Wolfsburg,de Bundesliga,28,34.0,41,411,147,35.8,12.09,4.32,0.09,0.27,17.7,17,2,3,39.2,36.7,0.09,1.8,2.3
95,Wolves,eng Premier League,27,38.0,47,425,153,36.0,11.18,4.03,0.10,0.28,16.7,12,4,4,46.7,43.6,0.11,0.3,-0.6

In [11]:
df.to_excel('TirosEquipo2324.xlsx',index=False)